import datetime


CONFIG_TEMPLATE = """# CrawlerConfig.py - This configuration is generated by CrawlerPlayground

from IntelligenceCrawler.CrawlPipeline import *

# === Crawler Configuration ===
CRAWLER_CONFIG = {{
    # === Fetcher init parameters ===
    'd_fetcher_name': '{d_fetcher_class}',
    'd_fetcher_init_param': {d_fetcher_init_param_code},

    'e_fetcher_name': '{e_fetcher_class}',
    'e_fetcher_init_param': {e_fetcher_init_param_code},

    'discoverer_name': '{discoverer_class}',
    'discoverer_init_param': {discoverer_init_param_code},

    'extractor_name': '{extractor_class}',
    'extractor_init_param': {extractor_init_param_code},

    # === Crawl parameters ===
    'entry_points': {entry_points_code},
    'period_filter': {period_filter_code},
    'channel_filter': {channel_filter_code},
    'd_fetcher_kwargs': {d_fetcher_kwargs_code},
    'e_fetcher_kwargs': {e_fetcher_kwargs_code},
    'extractor_kwargs': {extractor_kwargs_code},

    # === Handler functions (to be implemented by user) ===
    'article_filter': None,
    'content_handler': None,
    'exception_handler': None,
}}


if __name__ == "__main__":
    import traceback
    try:
        from IntelligenceCrawler.CrawlPipeline import run_pipeline
        run_pipeline(CRAWLER_CONFIG)
    except Exception as e:
        print(str(e))
        print(traceback.format_exc())
"""


class CrawlerConfigGenerator:
    """Generates crawler configuration in dictionary format instead of executable code."""

    def generate_config_from_config(self, config: dict) -> str:
        """
        Takes a configuration dict and generates a configuration dictionary
        instead of executable Python code.

        Args:
            config: Configuration dictionary from UI

        Returns:
            String representation of the configuration Python file
        """
        # Class name mappings (same as before)
        DISCOVERER_NAME_MAP = {
            "Sitemap": "SitemapDiscoverer",
            "RSS": "RSSDiscoverer",
            "Smart Analysis": "ListPageDiscoverer"
        }

        FETCHER_NAME_MAP = {
            "Simple (Requests)": "RequestsFetcher",
            "Advanced (Playwright)": "PlaywrightFetcher",
            "Stealth (Playwright)": "PlaywrightFetcher"
        }

        EXTRACTOR_NAME_MAP = {
            "PassThrough": 'PassThroughExtractor',
            "Trafilatura": 'TrafilaturaExtractor',
            "Readability": 'ReadabilityExtractor',
            "Newspaper3k": 'Newspaper3kExtractor',
            "Generic CSS": 'GenericCSSExtractor',
            "Crawl4AI": 'Crawl4AIExtractor',
        }

        # Extract configuration sections
        d_config = config['discoverer']
        e_config = config['extractor']
        d_fetcher_config = d_config['fetcher']
        e_fetcher_config = e_config['fetcher']

        # Map class names
        discoverer_class = DISCOVERER_NAME_MAP.get(d_config['class'], "UnknownDiscoverer")
        d_fetcher_class = FETCHER_NAME_MAP.get(d_fetcher_config['class'], "UnknownFetcher")
        extractor_class = EXTRACTOR_NAME_MAP.get(e_config['class'], "UnknownExtractor")
        e_fetcher_class = FETCHER_NAME_MAP.get(e_fetcher_config['class'], "UnknownFetcher")

        # Generate parameter codes for each section
        d_fetcher_init_param_code = self._generate_fetcher_params_code(d_fetcher_class, d_fetcher_config['parameters'])
        e_fetcher_init_param_code = self._generate_fetcher_params_code(e_fetcher_class, e_fetcher_config['parameters'])
        discoverer_init_param_code = self._generate_discoverer_params_code(discoverer_class, d_config['args'])
        extractor_init_param_code = self._generate_extractor_params_code(extractor_class, e_config.get('args', {}))

        # Generate crawl parameters
        entry_points_code = self._generate_entry_points_code(d_config['args'])
        period_filter_code = self._generate_period_filter_code(d_config['args'])
        channel_filter_code = self._generate_channel_filter_code(config.get('channel_filter', {}))
        d_fetcher_kwargs_code = repr(d_config.get('fetcher_kwargs', {}))
        e_fetcher_kwargs_code = repr(e_config.get('fetcher_kwargs', {}))
        extractor_kwargs_code = repr(e_config.get('args', {}))

        # Format the final configuration
        config_code = CONFIG_TEMPLATE.format(
            d_fetcher_class=d_fetcher_class,
            e_fetcher_class=e_fetcher_class,
            discoverer_class=discoverer_class,
            extractor_class=extractor_class,
            d_fetcher_init_param_code=d_fetcher_init_param_code,
            e_fetcher_init_param_code=e_fetcher_init_param_code,
            discoverer_init_param_code=discoverer_init_param_code,
            extractor_init_param_code=extractor_init_param_code,
            entry_points_code=entry_points_code,
            period_filter_code=period_filter_code,
            channel_filter_code=channel_filter_code,
            d_fetcher_kwargs_code=d_fetcher_kwargs_code,
            e_fetcher_kwargs_code=e_fetcher_kwargs_code,
            extractor_kwargs_code=extractor_kwargs_code
        )

        return config_code

    def _generate_fetcher_params_code(self, fetcher_class: str, params: dict) -> str:
        """Generate fetcher initialization parameters."""
        fetcher_params = {'log_callback': 'print'}

        if 'Playwright' in fetcher_class:
            fetcher_params.update({
                'proxy': params.get('proxy'),
                'timeout_s': params.get('timeout'),
                'stealth': params.get('stealth', False),
                'pause_browser': params.get('pause_browser', False),
                'render_page': params.get('render_page', False)
            })
        elif 'Requests' in fetcher_class:
            fetcher_params.update({
                'proxy': params.get('proxy'),
                'timeout_s': params.get('timeout')
            })

        return self._dict_to_config_str(fetcher_params)

    def _generate_discoverer_params_code(self, discoverer_class: str, args: dict) -> str:
        """Generate discoverer initialization parameters."""
        discoverer_params = {'verbose': True}

        if discoverer_class == "ListPageDiscoverer":
            discoverer_params.update({
                'manual_specified_signature': args.get('manual_specified_signature'),
                'scope_selector': args.get('scope_selector')
            })

        return self._dict_to_config_str(discoverer_params)

    def _generate_extractor_params_code(self, extractor_class: str, args: dict) -> str:
        """Generate extractor initialization parameters."""
        # Basic extractor parameters - can be extended based on specific extractor needs
        extractor_params = {'verbose': True}
        return self._dict_to_config_str(extractor_params)

    def _generate_entry_points_code(self, args: dict) -> str:
        """Generate entry points configuration."""
        entry_point = args.get('entry_point')
        # In your example, you have multiple entry points from the links
        # For now, using single entry point, but can be extended to support multiple
        return repr([entry_point] if entry_point else [])

    def _generate_period_filter_code(self, args: dict) -> str:
        """Generate period filter configuration."""
        if args.get('date_filter_enabled'):
            days_ago = args['date_filter_days']
            end_date = datetime.datetime.now()
            start_date = end_date - datetime.timedelta(days=days_ago)
            return f"(datetime.datetime.fromisoformat('{start_date.isoformat()}'), datetime.datetime.fromisoformat('{end_date.isoformat()}'))"
        else:
            return "(None, None)"

    def _generate_channel_filter_code(self, filter_config: dict) -> str:
        """Generate channel filter configuration."""
        checked_keys = filter_config.get('channel_filter_keys', [])
        channel_filter = {'channel_list_filter': checked_keys}
        return self._dict_to_config_str(channel_filter)

    def _dict_to_config_str(self, param_dict: dict) -> str:
        """Convert dictionary to configuration string representation."""
        # Special handling for log_callback and other callbacks
        formatted_items = []
        for key, value in param_dict.items():
            if key == 'log_callback' and value == 'print':
                formatted_items.append(f"'{key}': print")
            elif isinstance(value, str):
                formatted_items.append(f"'{key}': '{value}'")
            elif value is None:
                formatted_items.append(f"'{key}': None")
            else:
                formatted_items.append(f"'{key}': {value}")

        return "{" + ", ".join(formatted_items) + "}"


# Optional: Maintain backward compatibility with existing code generation
class CrawlerCodeGenerator:
    """Legacy code generator - can be deprecated over time"""

    def generate_code_from_config(self, config: dict) -> str:
        """
        Legacy method that now uses the new config generator
        and wraps it in executable code template for backward compatibility.
        """
        config_generator = CrawlerConfigGenerator()
        config_str = config_generator.generate_config_from_config(config)
        return config_str
