# -*- coding: utf-8 -*-
"""
CrawlerCodeGenerator — 扁平配置代码生成器

设计目标：
- 直接消费扁平 CRAWLER_CONFIG 结构
- 使用 pprint.pformat() 替代模板字符串拼接
- 无需维护 _generate_*_code() 辅助方法
- 新增字段自动生成，无需修改 Generator
"""
import pprint


USAGE_FOOTER = '''
# ------ Usage example and demo. Can be deleted. ------

if __name__ == "__main__":
    import traceback
    try:
        from IntelligenceCrawler.CrawlPipeline import run_pipeline, save_article_to_disk
        CRAWLER_CONFIG['content_handler'] = save_article_to_disk
        run_pipeline('default', CRAWLER_CONFIG)
    except Exception as e:
        print(str(e))
        print(traceback.format_exc())
'''


class CrawlerCodeGenerator:
    """Generates executable Python code from a flat CRAWLER_CONFIG dictionary."""

    def generate_code_from_config(self, config: dict) -> str:
        """
        Takes a **flat** configuration dict (as produced by Playground's
        _build_flat_config_dict) and generates a Python script containing
        CRAWLER_CONFIG.

        Args:
            config: Flat dict with keys like d_fetcher_name, discoverer_name,
                    entry_points, period_filter, etc.

        Returns:
            Executable Python code string.
        """
        # Replace un-serializable callables with marker strings before pprint,
        # then replace markers back to bare identifiers in the output string.
        MARKER_PRINT = "__PY_BARE_PRINT__"

        def _replace_callables(obj):
            if callable(obj) and obj is print:
                return MARKER_PRINT
            if isinstance(obj, dict):
                return {k: _replace_callables(v) for k, v in obj.items()}
            if isinstance(obj, (list, tuple)):
                replaced = [_replace_callables(v) for v in obj]
                return type(obj)(replaced)
            return obj

        sanitized = _replace_callables(config)
        config_str = pprint.pformat(sanitized, indent=4, width=100, sort_dicts=False)
        config_str = config_str.replace(f"'{MARKER_PRINT}'", "print")

        return f"""# CrawlerConfig.py - This configuration is generated by CrawlerPlayground
import datetime

# === Crawler Configuration ===
CRAWLER_CONFIG = {config_str}
{USAGE_FOOTER}"""
