# CrawlerGenerated.py - This code is generated by CrawlerPlayground

CRAWLER_CONFIG = {
    # === Fetcher init parameters ===
    'd_fetcher_name': 'PlaywrightFetcher',
    'd_fetcher_init_param': {'log_callback': print, 'proxy': None, 'timeout_s': 10, 'stealth': True, 'pause_browser': False, 'render_page': False},

    'e_fetcher_name': 'PlaywrightFetcher',
    'e_fetcher_init_param': { 'log_callback': print, 'proxy': None, 'timeout_s': 20, 'stealth': True, 'pause_browser': False, 'render_page': True},

    'discoverer_name': 'ListPageDiscoverer',
    'discoverer_init_param': {'verbose': True, 'manual_specified_signature': None},

    'extractor_name': 'TrafilaturaExtractor',
    'extractor_init_param': {'verbose': True},

    # === Crawl parameters ===

    # ------ Discoverer ------

    'entry_points': ['https://tass.com/world', 'https://tass.com/emergencies', 'https://tass.com/politics', 'https://tass.com/economy', 'https://tass.com/defense', 'https://tass.com/society'],
    'period_filter': ( None, None),
    'channel_filter': { 'channel_list_filter': [] },
    'd_fetcher_kwargs': {'wait_until': 'networkidle', 'wait_for_selector': None, 'wait_for_timeout_s': 10, 'scroll_pages': 5},

    # ------ Extractor ------

    'article_filter': None,
    'content_handler': None,
    'exception_handler': None,
    'e_fetcher_kwargs': {'wait_until': 'networkidle', 'wait_for_selector': None, 'wait_for_timeout_s': 20, 'scroll_pages': 0},
    'extractor_kwargs': { }
}


if __name__ == "__main__":
    import traceback
    try:
        from IntelligenceCrawler.CrawlPipeline import run_pipeline
        run_pipeline(CRAWLER_CONFIG)
    except Exception as e:
        print(str(e))
        print(traceback.format_exc())
