import os
import sys
import datetime
import traceback
from collections import deque
from urllib.parse import urlparse
from typing import List, Dict, Any, Optional


CODE_TEMPLATE = """# CrawlerGenerated.py - This code is generated by CrawlerPlayground

from IntelligenceCrawler.CrawlPipeline import *

# === Fetcher init parameters ===
d_fetcher_init_param = {d_fetcher_init_param_code}
e_fetcher_init_param = {e_fetcher_init_param_code}

# === Crawl parameters ===
{parameters}
{channel_filter_list}

def run_pipeline(
        article_filter = lambda url, group: True, 
        content_handler = save_article_to_disk, 
        exception_handler = lambda url, exception: None,
        crawler_governor: Optional[GovernanceManager] = None
):
    # === 1. Initialize Components ===
    d_fetcher = {d_fetcher_class}(**d_fetcher_init_param)
    e_fetcher = {e_fetcher_class}(**e_fetcher_init_param)
    {code_discoverer}
    {code_extractor}

    # === 2. Build pipeline ===
    pipeline = CrawlPipeline(
        d_fetcher=d_fetcher,
        discoverer=discoverer,
        e_fetcher=e_fetcher,
        extractor=extractor,
        log_callback=log_cb,
        crawler_governor=crawler_governor
    )

    # Step 1: Discover all channels
    pipeline.discover_channels(entry_point, start_date, end_date,
                               fetcher_kwargs=d_fetcher_kwargs)

    # Step 2: Discover and fetch articles (populates pipeline.contents)
    pipeline.discover_articles(channel_filter=partial(
        common_channel_filter, channel_filter_list=channel_filter_list),
        fetcher_kwargs=d_fetcher_kwargs)

    # Step 3: Extract content and run handlers
    pipeline.extract_articles(
        article_filter=article_filter,
        content_handler=content_handler,
        exception_handler=exception_handler,
        fetcher_kwargs=e_fetcher_kwargs,
        extractor_kwargs=extractor_kwargs
    )


if __name__ == "__main__":
    try:
        run_pipeline()
    except Exception as e:
        print(str(e))
        print(traceback.format_exc())
"""


class CrawlerCodeGenerator:
    def generate_code_from_config(self, config: dict) -> str:
        """
        Takes a configuration dict and generates a simple, runnable
        Python script based on the new 'CrawlProcess' architecture.
        (根据新的 'CrawlProcess' 架构，获取配置字典并生成一个简单的、
         可运行的Python脚本。)
        """
        # --- 1. Class Name Mappings (The "Table" Lookup) ---
        DISCOVERER_NAME_MAP = {
            "Sitemap": "SitemapDiscoverer",
            "RSS": "RSSDiscoverer",
            "Smart Analysis": "ListPageDiscoverer"
        }

        FETCHER_NAME_MAP = {
            "Simple (Requests)": "RequestsFetcher",
            "Advanced (Playwright)": "PlaywrightFetcher",
            "Stealth (Playwright)": "PlaywrightFetcher"
        }

        EXTRACTOR_NAME_MAP = {
            "PassThrough": 'PassThroughExtractor',
            "Trafilatura": 'TrafilaturaExtractor',
            "Readability": 'ReadabilityExtractor',
            "Newspaper3k": 'Newspaper3kExtractor',
            "Generic CSS": 'GenericCSSExtractor',
            "Crawl4AI": 'Crawl4AIExtractor',
        }

        # 1. 生成渠道过滤器列表代码
        channel_filter_list = config.get("channel_filter", [])
        channel_list_code = self._generate_channel_filter_list_code(channel_filter_list)

        # --- 2. Get Discovery Config ---
        d_config = config['discoverer']
        d_fetcher_config = d_config['fetcher']

        d_class_name = DISCOVERER_NAME_MAP.get(d_config['class'], "UnknownDiscoverer")
        d_fetcher_class_name = FETCHER_NAME_MAP.get(d_fetcher_config['class'], "UnknownFetcher")

        # --- Build Discovery Fetcher Args ---
        d_fetcher_params = d_fetcher_config['parameters']
        d_fetcher_kwargs_str = repr(d_config.get('fetcher_kwargs', {}))

        # --- 3. Get Extraction Config ---
        e_config = config['extractor']
        e_fetcher_config = e_config['fetcher']

        e_class_name = EXTRACTOR_NAME_MAP.get(e_config['class'], "UnknownDiscoverer")
        e_fetcher_class_name = FETCHER_NAME_MAP.get(e_fetcher_config['class'], "UnknownFetcher")

        # --- Build Extraction Fetcher Args ---
        e_fetcher_params = e_fetcher_config['parameters']
        e_arg_list = ['log_callback=log_cb']

        e_fetcher_kwargs_str = repr(e_config.get('fetcher_kwargs', {}))
        extractor_kwargs_str = repr(e_config.get('args', {}))

        d_fetcher_init_param_code, e_fetcher_init_param_code = (
            self._generate_fetcher_init_params_code(
                d_fetcher_class_name, d_fetcher_params,
                e_fetcher_class_name, e_fetcher_params))

        # --- 4. Build {parameters} String ---

        if d_class_name == "ListPageDiscoverer":
            ai_sig_val = d_config['args'].get('manual_specified_signature')
            scope_sel_val = d_config['args'].get('scope_selector')
            code_discoverer = (
                f"discoverer = {d_class_name}(fetcher=d_fetcher, verbose=True, "
                f"manual_specified_signature={repr(ai_sig_val)}, "
                f"scope_selector={repr(scope_sel_val)})"
            )
        else:
            # Default for Sitemap, RSS, etc.
            code_discoverer = f"discoverer = {d_class_name}(fetcher=d_fetcher, verbose=True)"

        code_extractor = f"extractor = {e_class_name}(verbose=True)"

        parameters = []
        entry_point_value = d_config['args'].get('entry_point')
        parameters.append(f"entry_point = {repr(entry_point_value)}")

        if d_config['args'].get('date_filter_enabled'):
            parameters.append(f"days_ago = {d_config['args']['date_filter_days']}")
            parameters.append("end_date = datetime.datetime.now()")
            parameters.append("start_date = end_date - datetime.timedelta(days=days_ago)")
        else:
            parameters.append("start_date = None")
            parameters.append("end_date = None")

        # 添加所有 kwargs 字典
        parameters.append(f"d_fetcher_kwargs = {d_fetcher_kwargs_str}")
        parameters.append(f"e_fetcher_kwargs = {e_fetcher_kwargs_str}")
        parameters.append(f"extractor_kwargs = {extractor_kwargs_str}")

        parameters_str = "\n".join(parameters)

        # TODO: Get value from ui
        in_markdown = True
        in_pdf = True

        # --- 5. Format the final code ---
        code = CODE_TEMPLATE.format(
            d_fetcher_class=d_fetcher_class_name,
            e_fetcher_class=e_fetcher_class_name,
            d_fetcher_init_param_code=d_fetcher_init_param_code,
            e_fetcher_init_param_code=e_fetcher_init_param_code,
            code_discoverer=code_discoverer,
            code_extractor=code_extractor,
            parameters=parameters_str,
            channel_filter_list=channel_list_code,
            in_markdown=in_markdown,
            in_pdf=in_pdf
        )

        return code

    def _generate_fetcher_init_params_code(
            self,
            d_fetcher_class_name: str, d_fetcher_params: dict,
            e_fetcher_class_name: str, e_fetcher_params: dict,
    ):
        # --- Build Discovery Fetcher Init Parameters ---
        d_fetcher_init_param = {
            'log_callback': 'log_cb',  # 使用字符串占位符，最终在模板中格式化
        }

        if 'Playwright' in d_fetcher_class_name:
            d_fetcher_init_param['proxy'] = d_fetcher_params.get('proxy')
            d_fetcher_init_param['timeout_s'] = d_fetcher_params.get('timeout')
            d_fetcher_init_param['stealth'] = d_fetcher_params.get('stealth')
            d_fetcher_init_param['pause_browser'] = d_fetcher_params.get('pause_browser')
            d_fetcher_init_param['render_page'] = d_fetcher_params.get('render_page')
        elif 'Requests' in d_fetcher_class_name:
            d_fetcher_init_param['proxy'] = d_fetcher_params.get('proxy')
            d_fetcher_init_param['timeout_s'] = d_fetcher_params.get('timeout')

        # --- Build Extraction Fetcher Init Parameters ---
        e_fetcher_init_param = {
            'log_callback': 'log_cb',  # 使用字符串占位符，最终在模板中格式化
        }

        if 'Playwright' in e_fetcher_class_name:
            e_fetcher_init_param['proxy'] = e_fetcher_params.get('proxy')
            e_fetcher_init_param['timeout_s'] = e_fetcher_params.get('timeout')
            e_fetcher_init_param['stealth'] = e_fetcher_params.get('stealth')
            e_fetcher_init_param['pause_browser'] = e_fetcher_params.get('pause_browser')
            e_fetcher_init_param['render_page'] = e_fetcher_params.get('render_page')
        elif 'Requests' in e_fetcher_class_name:
            e_fetcher_init_param['proxy'] = e_fetcher_params.get('proxy')
            e_fetcher_init_param['timeout_s'] = e_fetcher_params.get('timeout')

        return (self._dict_to_dict_str(d_fetcher_init_param),
                self._dict_to_dict_str(e_fetcher_init_param))

    def _generate_channel_filter_list_code(self, filter_config: dict) -> str:
        """
        Generates the Python code string for 'channel_filter_list'
        based on the provided configuration dictionary.

        (根据提供的配置字典生成 'channel_filter_list' 的 Python 代码字符串。)
        """
        checked_keys = filter_config.get('channel_filter_keys', [])

        if not checked_keys:
            # Generate an empty list if no channels were checked
            return "channel_filter_list = []"

        # Format into a clean Python list string
        list_str = "channel_filter_list = [\n"
        for key in checked_keys:
            # repr() automatically handles quotes
            list_str += f"        {repr(key)},\n"
        list_str += "    ]"
        return list_str

    @staticmethod
    def _dict_to_arg_str(param_dict: dict) -> str:
        """Converts a parameter dict to a string of 'key=value' arguments."""
        arg_list = []
        for key, value in param_dict.items():
            # 特殊处理 log_callback，它始终是 log_cb (不带引号)
            if key == 'log_callback':
                arg_list.append(f"{key}=log_cb")
            else:
                # 使用 repr() 确保正确引用字符串和布尔值
                arg_list.append(f"{key}={repr(value)}")
        return ", ".join(arg_list)

    @staticmethod
    def _dict_to_dict_str(param_dict: dict) -> str:
        """Converts a parameter dict to a string representing a Python dict literal."""
        item_list = []
        for key, value in param_dict.items():
            # 键必须是字符串，用 repr() 确保正确引用
            key_str = repr(key)

            if key == 'log_callback':
                # 特殊处理 log_callback，值是 log_cb (不带引号)
                value_str = 'log_cb'
            else:
                # 使用 repr() 确保其他值的正确引用 (字符串带引号，数字/布尔不带)
                value_str = repr(value)

            item_list.append(f"{key_str}: {value_str}")

        return "{" + ", ".join(item_list) + "}"
