# CrawlerGenerated.py - This code is generated by CrawlerPlayground

from IntelligenceCrawler.CrawlPipeline import *
from IntelligenceCrawler.Discoverer import discoverer_factory
from IntelligenceCrawler.Extractor import extractor_factory
from IntelligenceCrawler.Fetcher import fetcher_factory

CRAWLER_CONFIG = {
    # === Fetcher init parameters ===
    'd_fetcher_name': 'PlaywrightFetcher',
    'd_fetcher_init_param': {'log_callback': log_cb, 'proxy': None, 'timeout_s': 10, 'stealth': True, 'pause_browser': False, 'render_page': False},

    'e_fetcher_name': 'PlaywrightFetcher',
    'e_fetcher_init_param': { 'log_callback': log_cb, 'proxy': None, 'timeout_s': 20, 'stealth': True, 'pause_browser': False, 'render_page': True},

    'discoverer_name': 'ListPageDiscoverer',
    'discoverer_init_param': {'verbose': True, 'manual_specified_signature': None},

    'extractor_name': 'TrafilaturaExtractor',
    'extractor_init_param': {'verbose': True},

    # === Crawl parameters ===

    # ------ Discoverer ------

    'entry_points': ['https://tass.com/world', 'https://tass.com/emergencies', 'https://tass.com/politics', 'https://tass.com/economy', 'https://tass.com/defense', 'https://tass.com/society'],
    'period_filter': ( None, None),
    'channel_filter': { 'channel_list_filter': [] },
    'd_fetcher_kwargs': {'wait_until': 'networkidle', 'wait_for_selector': None, 'wait_for_timeout_s': 10, 'scroll_pages': 5},

    # ------ Extractor ------

    'article_filter': None,
    'content_handler': None,
    'exception_handler': None,
    'e_fetcher_kwargs': {'wait_until': 'networkidle', 'wait_for_selector': None, 'wait_for_timeout_s': 20, 'scroll_pages': 0},
    'extractor_kwargs': { }
}


def build_pipeline(config: dict):
    d_fetcher_name = config.get('d_fetcher_name', 'N/A')
    d_fetcher_init_param = config.get('d_fetcher_init_param', {})
    d_fetcher = fetcher_factory(d_fetcher_name, d_fetcher_init_param)

    e_fetcher_name = config.get('e_fetcher_name', 'N/A')
    e_fetcher_init_param = config.get('e_fetcher_init_param', {})
    e_fetcher = fetcher_factory(e_fetcher_name, e_fetcher_init_param)

    discoverer_name = config.get('discoverer_name', 'N/A')
    discoverer_init_param = config.get('discoverer_init_param', {})
    discoverer = discoverer_factory(discoverer_name, { 'fetcher': d_fetcher, **discoverer_init_param} )

    extractor_name = config.get('extractor_name', 'N/A')
    extractor_init_param = config.get('extractor_init_param', {})
    extractor = extractor_factory(extractor_name, extractor_init_param)

    pipeline = CrawlPipeline(
        d_fetcher=d_fetcher,
        discoverer=discoverer,
        e_fetcher=e_fetcher,
        extractor=extractor,
        log_callback=log_cb
    )
    return pipeline


def drive_pipeline(pipeline: CrawlPipeline, config: dict):
    entry_points = config.get('entry_points', [])
    start_date, end_date = config.get('period_filter', (None, None))
    d_fetcher_kwargs = config.get('d_fetcher_kwargs', {})

    # ============== 1. Discover Channels ==============

    pipeline.discover_channels(
        entry_point=entry_points,
        start_date=start_date,
        end_date=end_date,
        fetcher_kwargs=d_fetcher_kwargs)

    # ============== 2. Discover Articles ==============

    # Only support channel_list_filter
    channel_filter = config.get('channel_filter', {})
    if 'channel_list_filter' in channel_filter:
        channel_list_filter_params = channel_filter['channel_list_filter']
        channel_filter = partial(common_channel_filter, channel_filter_list=channel_list_filter_params)
    else:
        channel_filter = None

    pipeline.discover_articles(
        channel_filter=channel_filter,
        fetcher_kwargs=d_fetcher_kwargs)

    # =============== 3. Extract Articles ===============

    article_filter = config.get('article_filter', None)
    content_handler = config.get('content_handler', None)
    exception_handler = config.get('exception_handler', None)

    e_fetcher_kwargs = config.get('e_fetcher_kwargs', { })
    extractor_kwargs = config.get('extractor_kwargs', { })

    pipeline.extract_articles(
        article_filter=article_filter,
        content_handler=content_handler,
        exception_handler=exception_handler,
        fetcher_kwargs=e_fetcher_kwargs,
        extractor_kwargs=extractor_kwargs
    )

def run_pipeline():
    pipeline = build_pipeline(CRAWLER_CONFIG)
    drive_pipeline(pipeline, CRAWLER_CONFIG)



if __name__ == "__main__":
    try:
        run_pipeline()
    except Exception as e:
        print(str(e))
        print(traceback.format_exc())
